### ISSUE TITLE
understanding the code

### ISSUE THREAD

**Issue by vincentme** [DylanWusee/PointPWC#10]
Hi, I would like your help to understand the code. It seems that the code does not match the description in the paper. 

1. Class PointConvFlow should be the function to calculate the cost volume. But the computation looks like not match the description in figure 2. 
2. Also the class PointConvD should be the PointConv in "PointConv: Deep Convolutional Networks on 3D Point Clouds". Seems not match figure 3 of that paper. For instance, the shape of weight is (B, C, K, N), not (K, Cin*Cout) in the figure. 

Thanks in advance!

**Comment by DylanWusee** [comment]
Hi, 

Thank you for your interest in our work!

For the first question, The PointConvFlow actually only computes the first part of the cost volume in Figure2, which is the Point-to-Patch Cost Volume. The second part of the cost volume aggregation is achieved by the first PointConv layer in the Flow Estimator. We find this PointConv layer is critical for the scene flow estimation. 

For the second question, the PointConv we use in this work is the Efficient version of PointConv, which is the Figure 5 of the original PointConv paper. The only different is that we drop the inverse density scale for efficiency and hyper-parameter tuning issues. Hence, the weight shape should be (B, C_mid, K, N).

Hope this helps for your understanding!

**Comment by vincentme** [comment]
Thanks for your explanation. It is much more clear to me now!
