### ISSUE TITLE
Creation of demo gif

### ISSUE THREAD

**Issue by shiba24** [DylanWusee/PointPWC#16]
Hi authors,

thank you for this great work and open-sourcing the codes.
This is a bit more request - can I ask you how you made the demo gif file like https://github.com/DylanWusee/PointPWC/blob/master/images/Kitti.gif ?

I'd also like to visualize my warp result like yours.

Sincerely

**Comment by DylanWusee** [comment]
Sorry for the late reply!

This gif is converted from an avi video.
And, I wrote a matlab script to play the point cloud.
