### ISSUE TITLE
Different Pointcloud Sizes

### ISSUE THREAD

**Issue by shreyas23** [DylanWusee/PointPWC#17]
Hi Dylan, 

Great work! Does this codebase support pointclouds with different numbers of points? The paper mentions that the method is applicable to pairs of pointclouds with different numbers of points, however, the pre-processing stage seem to assume the same number of points. Do you have any solutions that you recommend in regards to the augmentations and sampling (or the order in which these two are done)?

**Comment by DylanWusee** [comment]
The algorithm itself does not specify the number of points.

You can try to adjust the number of points in the config file.
