### ISSUE TITLE
About Self-supervised Training

### ISSUE THREAD

**Issue by Holycomfort** [DylanWusee/PointPWC#8]
Thank you for your great code. However I found it hard to reproduce the self-supervised results reported in your paper.
I wonder if you could release this part of code. 
Thank you!

**Comment by DylanWusee** [comment]
I added a branch self_loss. It includes a naive implementation of self_supervised loss there, which is the "multiScaleChamferSmoothCurvature".

**Comment by DylanWusee** [comment]
Code is merged into master.
